export const PRODUTOS_SELECT = [
  { label: "Bolo chocolate", value: 0 },
  { label: "Brigadeiro", value: 1 },
  { label: "Copo da felicidade", value: 2 },
  { label: "Barra de chocolate", value: 3 },
  { label: "Panetone", value: 4 },
];


export const PRODUTOS_PEDIDO: Array<any> = [
  {
    id: 1,
    desc: "Bolo chocolate",
    qtd: 5,
    custo: 6.0,
    desconto: 0,
    subTotal: 30.0,
  },
  {
    id: 2,
    desc: "Brigadeiro",
    qtd: 5,
    custo: 6.0,
    desconto: 0,
    subTotal: 30.0,
  },
  {
    id: 3,
    desc: "Copo da felicidade",
    qtd: 159,
    custo: 6.0,
    desconto: 0,
    subTotal: 30.0,
  },
  {
    id: 4,
    desc: "Brigadeiro",
    qtd: 5,
    custo: 6.0,
    desconto: 0,
    subTotal: 30.0,
  },
  {
    id: 5,
    desc: "Doce",
    qtd: 5,
    custo: 6.0,
    desconto: 0,
    subTotal: 30.0,
  },
  {
    id: 6,
    desc: "Bolo chocolate",
    qtd: 5,
    custo: 6.0,
    desconto: 0,
    subTotal: 30.0,
  },
  {
    id: 7,
    desc: "Brigadeiro",
    qtd: 5,
    custo: 6.0,
    desconto: 0,
    subTotal: 30.0,
  },
  {
    id: 8,
    desc: "Copo da felicidade",
    qtd: 159,
    custo: 6.0,
    desconto: 0,
    subTotal: 30.0,
  },
  {
    id: 9,
    desc: "Brigadeiro",
    qtd: 5,
    custo: 6.0,
    desconto: 0,
    subTotal: 30.0,
  },
  {
    id: 10,
    desc: "Doce10",
    qtd: 5,
    custo: 6.0,
    desconto: 0,
    subTotal: 30.0,
  },
];
