
export const ROWS = [
  {
    id: 1,
    nome: "Bolo chocolate",
    tipo: "DOCE",
    venda_em: "G",
    vlr_venda: 10,
    qtd: 5,
    custo: 6.0,
    desconto: 0,
    subTotal: 30.0,
  },
  {
    id: 2,
    nome: "Brigadeiro",
    tipo: "DOCE",
    venda_em: "UND",
    vlr_venda: 10,
    qtd: 5,
    custo: 6.0,
    desconto: 0,
    subTotal: 30.0,
  },
  {
    id: 3,
    nome: "Copo da felicidade",
    tipo: "DOCE",
    venda_em: "UND",
    vlr_venda: 10,
    qtd: 159,
    custo: 6.0,
    desconto: 0,
    subTotal: 30.0,
  },
  {
    id: 4,
    nome: "Brigadeiro",
    tipo: "DOCE",
    venda_em: "UND",
    vlr_venda: 10,
    qtd: 5,
    custo: 6.0,
    desconto: 0,
    subTotal: 30.0,
  },
  {
    id: 5,
    nome: "Doce",
    tipo: "DOCE",
    venda_em: "UND",
    vlr_venda: 10,
    qtd: 5,
    custo: 6.0,
    desconto: 0,
    subTotal: 30.0,
  },
  {
    id: 6,
    nome: "Bolo chocolate",
    tipo: "DOCE",
    venda_em: "G",
    vlr_venda: 10,
    qtd: 5,
    custo: 6.0,
    desconto: 0,
    subTotal: 30.0,
  },
  {
    id: 7,
    nome: "Brigadeiro",
    tipo: "DOCE",
    venda_em: "UND",
    vlr_venda: 10,
    qtd: 5,
    custo: 6.0,
    desconto: 0,
    subTotal: 30.0,
  },
  {
    id: 8,
    nome: "Copo da felicidade",
    tipo: "DOCE",
    venda_em: "UND",
    vlr_venda: 10,
    qtd: 159,
    custo: 6.0,
    desconto: 0,
    subTotal: 30.0,
  },
  {
    id: 9,
    nome: "Brigadeiro",
    tipo: "DOCE",
    venda_em: "CENTO",
    vlr_venda: 10,
    qtd: 5,
    custo: 6.0,
    desconto: 0,
    subTotal: 30.0,
  },
  {
    id: 10,
    nome: "Salgado",
    tipo: "SALGADO",
    venda_em: "CENTO",
    vlr_venda: 10,
    qtd: 5,
    custo: 6.0,
    desconto: 0,
    subTotal: 30.0,
  },
];
